app/main/urls.py
# app/main/urls.py

# Django modules
from django.urls import path

# My modules
from app.main import views

# Appname
app_name = 'main'

# Urlspatterns
urlpatterns = [
    # http://127.0.0.1:8000/blog/
    path('blog/', views.home_view, name='home'),
    # http://127.0.0.1:8000/blog/about/
    path('blog/about/', views.about_view, name='about'),
]

config/urls.py
# config/urls.py

# Django modules
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # main
    # http://127.0.0.1:8000/
    path('', include('app.main.urls', namespace='main')), # baru
    # admin
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/main/models.py
from django.db import models

# Create your models here.

app/main/views.py
# app/main/views.py

# Django modules
from django.shortcuts import render


def home_view(request):
    page_title = "Home" # baru
    context_dict = {'title':page_title} # baru
    return render(request, 'main/index.html', context_dict) # baru
    

def about_view(request):
    page_title = "About" # baru
    context_dict = {'title':page_title} # baru
    return render(request, 'main/about.html', context_dict) # baru

templates/base.html
<!-- templates/main/index.html -->
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog Word Count 80 | {% block title %} {{ block.super }} {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/testing.css' %}">
</head>
<body>
    <!-- header -->
    {% include 'inc/header.html' %}
    <!-- header ends-->

    <!-- content -->
    {% block content %}
    {% endblock content %}
    <!-- content ends -->

    <!-- footer -->
    {% include 'inc/footer.html' %}
    <!-- footer -->
</body>
</html>

templates/inc/footer.html
    <hr>

    <p>&copy; Skill_Sets Training 2024, Developed with <span style="color:red;">&hearts;</span> by ING </p>

templates/inc/header.html
    <nav>
        <a href="{% url 'main:home' %}">Home</a>
        <a href="{% url 'main:about' %}">About</a>
    </nav>

templates/main/about.html
<!-- templates/main/about.html -->
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}

    <h1>Ini adalah Laman About</h1>

    <h3>Title: {{ title }}</h3>

{% endblock content %}
    

templates/main/index.html
<!-- templates/main/index.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}

    <h1>Selamat Datang di Blog Word Count 80</h1>
    <p>Share postingan Anda di sini.</p>

    <h3>Title: {{ title }}</h3>
    <img src="{% static 'images/01.png' %}" width="50%">

{% endblock content %}